### ISSUE TITLE
Error with CORS

### ISSUE THREAD

**Issue by Kvin3324** [Kvin3324/bizzy#38]
When fetch on every pages: `/`, `forgot_password_form`, `reset_pswd_form`
=> 

![image](https://user-images.githubusercontent.com/29613292/80596471-b3505c80-8a26-11ea-8f2b-3019e5801915.png)

**Comment by luctst** [comment]
Je viens de test sur firefox et sur chrome et ça fonctionne pour moi, du coup me faudrait plus d'infos sur comment tu fais ça ? @Kvin3324

**Comment by Kvin3324** [comment]
Normalement j'avais mit plus d'infos mais elles n'ont pas été save, cool...
Sinon c'est quand je veux me connecter, inscrire ou `forgot_pswd`, lorsque je vais `fetch` j'ai cette erreur ! 
Et celle-ci côté bakc: `Unhandled rejection: { MongoServerSelectionError: connection <monitor> to 3.122.169.18:27017 closed`.

De plus, je teste celà sur plusieurs branch `feat/api_reset_pswd` & `feat/refonte_front`.

Je change bien le port dans le file `responseServer.js` mais ça ne change rien...

**Comment by luctst** [comment]
Ok je vois mais du coup si la connexion à la bdd est close ça doit venir de la.
